language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t oddsha/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true oddsha/react-test npm test

after_success:
  - docker build -t oddsha/multi-client ./client
  - docker build -t oddsha/multi-nginx ./nginx
  - docker build -t oddsha/multi-server ./server
  - docker build -t oddsha/multi-worker ./worker

#login to docker cli
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#Take those images and push them to docker hub
- docker push oddsha/multi-client
- docker push oddsha/multi-nginx
- docker push oddsha/multi-server
- docker push oddsha/multi-worker
